version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      discovery.type: single-node
      network.host: 0.0.0.0
      path.repo: /tmp/elastic4s
    ports:
      - 9200:9200
    volumes:
      - "./conf/docker/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "esdata1:/usr/share/elasticsearch/data:rw"
    restart: unless-stopped
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - "./conf/docker/redis.conf:/redis.conf"
      - "redis-data:/data:rw"
    command: >
      bash -c "redis-server --appendonly yes
      && redis-server /redis.conf"
    restart: always
  postgres:
    image: postgres
    container_name: pg-docker
    restart: always
    environment:
      POSTGRES_DB: inspiration_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata/
    ports:
      - 5432:5432
    volumes:
      - "./conf/docker/postgres.conf:/etc/postgresql/postgresql.conf"
      - "/var/lib/postgresql/data/:/var/lib/postgresql/data/pgdata"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
volumes:
  esdata1:
    driver: local
  redis-data: