version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      discovery.type: single-node
      network.host: 0.0.0.0
      path.repo: /tmp/elastic4s
    ports:
      # use obscure ports for the tests to reduce the risk of interfering with existing elastic installations/containers
      - 9200:9200
    volumes:
      - "./conf/docker/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - "./conf/docker/redis.conf:/redis.conf"
    command: [ "redis-server", "/redis.conf" ]
