name: Check for the SBT dependency vulnerabilities and print them on console
# Can be ignored by passing false boolean parameter while calling bash script dependencyCheck.sh

on:
  push:
    branches:
      - master

jobs:
  build_compile_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Dependency Check
        run: |
          sbt -v -Dfile.encoding=UTF-8 dependencyCheck
      - name: Print all the vulnerabilities
        run: |
          chmod +x ./.github/scripts/dependencyCheck.sh
          ./.github/scripts/dependencyCheck.sh "target/scala-2.13/dependency-check-report.json" false
        shell: bash