name: Publish Docker image for inspirational-quote-api CI

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      # setup Docker build action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Build image and push to GitHub Container Registry
        # https://github.com/docker/build-push-action
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          # Note: tags has to be all lower-case
          # Using GitHub tag ref name for the tags
          tags: ghcr.io/krishna-thapa/inspirational-quote-api/inspirational-quote-api:${{github.ref_name}}