name: Inspirational-quote-api CI

on:
  push:
    branches:
      - master

jobs:
  build_compile_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'sbt'
      - name: Scalafmt Action
        uses: AvaPL/scalafmt-native-formatter@v0
      - name: Run clean, compile and tests
        run: |
          sbt clean compile test
