name: Inspirational-quote-api CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Scalafmt Action
      uses: openlawteam/scalafmt-ci@v2.0.2
    - name: Run clean, compile and tests
      run: |
        sbt clean compile
        sbt test
      
