name: Inspirational-quote-api CI

on:
  push:
    branches:
      - master

jobs:
  build_compile_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Scalafmt Action
        run: sbt scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
      - name: Run clean, compile and tests
        run: |
          sbt clean compile
          sbt test