name: Inspirational-quote-api CI

on:
  push:
    branches:
      - master

jobs:
  build_compile_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Scalafmt Action
        run: sbt scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
      - name: Run clean, compile and tests
        run: |
          sbt clean compile
          sbt test
      - name: Dependency Check
        run: |
          sbt -v -Dfile.encoding=UTF-8 dependencyCheck
      - name: Print all the vulnerabilities
        run: |
          chmod +x ./.github/scripts/dependencyCheck.sh
          ./.github/scripts/dependencyCheck.sh "target/scala-2.13/dependency-check-report.json" true
        shell: bash
      - name: HTML Preview for Dependency check report # Won't work if previous run doesn't create HTML file
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
          html_file: 'target/scala-2.13/dependency-check-report.html'