# This workflow will launch at 00:00 every Sunday
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

name: Launch Scala Steward

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.REPO_GITHUB_TOKEN }}

# Make sure the account you choose has Name and Public email fields defined in
# Public Profile -- they will be used by Scala Steward to make commits.
# Using person token and email for testing purpose, once it is up and running, we should use the rps GitHub
# token and email